/**
 * Permission names, mirroring the backend's permission tree
 * (`Pages.Administration...`). Keep in sync with the definitions the
 * server exposes at `GET /auth/permissions`.
 */
export const Permissions = {
  administration: 'Pages.Administration',
  usersView: 'Pages.Administration.Users.View',
  usersCreate: 'Pages.Administration.Users.Create',
  usersEdit: 'Pages.Administration.Users.Edit',
  usersDelete: 'Pages.Administration.Users.Delete',
  usersPermissions: 'Pages.Administration.Users.Permissions',
  rolesView: 'Pages.Administration.Roles.View',
  rolesCreate: 'Pages.Administration.Roles.Create',
  rolesEdit: 'Pages.Administration.Roles.Edit',
  rolesDelete: 'Pages.Administration.Roles.Delete',
  tenantSettings: 'Pages.Administration.Tenant.Settings',
  auditLogsView: 'Pages.Administration.AuditLogs.View',

  accounting: 'Pages.Accounting',
  fiscalYearsView: 'Pages.Accounting.FiscalYears.View',
  fiscalYearsManage: 'Pages.Accounting.FiscalYears.Manage',
  accountsView: 'Pages.Accounting.Accounts.View',
  accountsCreate: 'Pages.Accounting.Accounts.Create',
  accountsEdit: 'Pages.Accounting.Accounts.Edit',
  accountsDelete: 'Pages.Accounting.Accounts.Delete',
  journalView: 'Pages.Accounting.Journal.View',
  journalCreate: 'Pages.Accounting.Journal.Create',
  journalPost: 'Pages.Accounting.Journal.Post',
  journalReverse: 'Pages.Accounting.Journal.Reverse',
  expensesView: 'Pages.Accounting.Expenses.View',
  expensesRecord: 'Pages.Accounting.Expenses.Record',
  taxView: 'Pages.Accounting.Tax.View',
  taxCreate: 'Pages.Accounting.Tax.Create',
  taxEdit: 'Pages.Accounting.Tax.Edit',
  taxDelete: 'Pages.Accounting.Tax.Delete',
  accountingReportsView: 'Pages.Accounting.Reports.View',

  inventory: 'Pages.Inventory',
  itemsView: 'Pages.Inventory.Items.View',
  itemsCreate: 'Pages.Inventory.Items.Create',
  itemsEdit: 'Pages.Inventory.Items.Edit',
  itemsDelete: 'Pages.Inventory.Items.Delete',
  warehousesView: 'Pages.Inventory.Warehouses.View',
  warehousesManage: 'Pages.Inventory.Warehouses.Manage',
  movementsView: 'Pages.Inventory.Movements.View',
  movementsCreate: 'Pages.Inventory.Movements.Create',
  movementsPost: 'Pages.Inventory.Movements.Post',
  movementsReverse: 'Pages.Inventory.Movements.Reverse',
  adjustmentsView: 'Pages.Inventory.Adjustments.View',
  adjustmentsCreate: 'Pages.Inventory.Adjustments.Create',
  adjustmentsPost: 'Pages.Inventory.Adjustments.Post',
  inventoryReportsView: 'Pages.Inventory.Reports.View',

  procurement: 'Pages.Procurement',
  suppliersView: 'Pages.Procurement.Suppliers.View',
  suppliersCreate: 'Pages.Procurement.Suppliers.Create',
  suppliersEdit: 'Pages.Procurement.Suppliers.Edit',
  suppliersDelete: 'Pages.Procurement.Suppliers.Delete',
  requisitionsView: 'Pages.Procurement.Requisitions.View',
  requisitionsCreate: 'Pages.Procurement.Requisitions.Create',
  requisitionsSubmit: 'Pages.Procurement.Requisitions.Submit',
  requisitionsApprove: 'Pages.Procurement.Requisitions.Approve',
  requisitionsConvert: 'Pages.Procurement.Requisitions.Convert',
  rfqsView: 'Pages.Procurement.Rfqs.View',
  rfqsCreate: 'Pages.Procurement.Rfqs.Create',
  rfqsSend: 'Pages.Procurement.Rfqs.Send',
  rfqsRecordQuotes: 'Pages.Procurement.Rfqs.RecordQuotes',
  rfqsAward: 'Pages.Procurement.Rfqs.Award',
  ordersView: 'Pages.Procurement.Orders.View',
  ordersCreate: 'Pages.Procurement.Orders.Create',
  ordersSubmit: 'Pages.Procurement.Orders.Submit',
  ordersApprove: 'Pages.Procurement.Orders.Approve',
  ordersCancel: 'Pages.Procurement.Orders.Cancel',
  receiptsView: 'Pages.Procurement.Receipts.View',
  receiptsCreate: 'Pages.Procurement.Receipts.Create',
  receiptsPost: 'Pages.Procurement.Receipts.Post',
  receiptsReverse: 'Pages.Procurement.Receipts.Reverse',
  returnsView: 'Pages.Procurement.Returns.View',
  returnsCreate: 'Pages.Procurement.Returns.Create',
  returnsPost: 'Pages.Procurement.Returns.Post',
  returnsReverse: 'Pages.Procurement.Returns.Reverse',
  purchaseInvoicesView: 'Pages.Procurement.Invoices.View',
  purchaseInvoicesCreate: 'Pages.Procurement.Invoices.Create',
  purchaseInvoicesPost: 'Pages.Procurement.Invoices.Post',
  purchaseInvoicesCancel: 'Pages.Procurement.Invoices.Cancel',
  procurementReportsView: 'Pages.Procurement.Reports.View',
} as const;
