import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { NgIcon } from '@ng-icons/core';
import { UiButton } from '../../../../shared/ui/button';
import { PageSkeleton } from '../../../../shared/ui/skeleton';
import { PageHeader } from '../../../../core/layout/page-header/page-header';
import { AuthService } from '../../../../core/auth/auth.service';
import { Permissions } from '../../../../core/auth/permissions.constants';
import { NotificationService } from '../../../../core/services/notification.service';
import { ConfirmService } from '../../../../core/services/confirm.service';
import { apiErrorInfo } from '../../../../shared/api/api-error';
import { fmtCost, fmtDate, fmtDateTime, fmtQty, statusLabel } from '../../shared/scm-format';
import {
  InventoryServiceProxy,
  MoveView,
} from '../../../../shared/service-proxies/service-proxies';

/** One stock movement with its lines; supports posting a draft and reversing a posting. */
@Component({
  selector: 'app-movement-detail-page',
  imports: [PageSkeleton, RouterLink, NgIcon, UiButton, PageHeader],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './movement-detail.page.html',
})
export class MovementDetailPage {
  private readonly proxy = inject(InventoryServiceProxy);
  private readonly auth = inject(AuthService);
  private readonly notify = inject(NotificationService);
  private readonly confirm = inject(ConfirmService);
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);

  readonly canCreate = computed(() => this.auth.hasPermission(Permissions.movementsCreate));
  readonly canPost = computed(() => this.auth.hasPermission(Permissions.movementsPost));
  readonly canReverse = computed(() => this.auth.hasPermission(Permissions.movementsReverse));

  readonly loading = signal(true);
  readonly error = signal<string | null>(null);
  readonly busy = signal(false);
  readonly move = signal<MoveView | null>(null);

  /** A movement generated by another document reverses only through its source. */
  readonly systemGenerated = computed(() => !!this.move()?.source);

  private id = '';

  readonly fmtQty = fmtQty;
  readonly fmtCost = fmtCost;
  readonly fmtDate = fmtDate;
  readonly fmtDateTime = fmtDateTime;
  readonly statusLabel = statusLabel;

  constructor() {
    this.route.paramMap.pipe(takeUntilDestroyed()).subscribe((params) => {
      this.id = params.get('id') ?? '';
      this.load();
    });
  }

  private load(): void {
    this.loading.set(true);
    this.error.set(null);
    this.proxy.get_move(this.id).subscribe({
      next: (m) => {
        this.move.set(m);
        this.loading.set(false);
      },
      error: (err) => {
        this.error.set(apiErrorInfo(err).message || 'Could not load the movement.');
        this.loading.set(false);
      },
    });
  }

  statusToneClass(status: string): string {
    return status === 'posted'
      ? 'bg-green-100 text-green-700 dark:bg-green-900/40 dark:text-green-300'
      : status === 'reversed'
        ? 'bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300'
        : 'bg-muted text-muted-foreground';
  }

  edit(): void {
    void this.router.navigate(['/inventory/movements', this.id, 'edit']);
  }

  post(): void {
    if (this.busy()) return;
    this.busy.set(true);
    this.proxy.post_move(this.id).subscribe({
      next: (m) => {
        this.busy.set(false);
        this.move.set(m);
        this.notify.success('Movement posted');
      },
      error: (err) => {
        this.busy.set(false);
        this.notify.error(apiErrorInfo(err).message || 'Could not post the movement.');
      },
    });
  }

  async remove(): Promise<void> {
    const m = this.move();
    if (!m || this.busy()) return;
    const ok = await this.confirm.ask({
      title: 'Delete this draft?',
      message: 'The draft movement and its lines are removed. Only drafts can be deleted.',
      confirmText: 'Delete',
      tone: 'danger',
    });
    if (!ok) return;
    this.busy.set(true);
    this.proxy.delete_move(this.id).subscribe({
      next: () => {
        this.busy.set(false);
        this.notify.success('Draft deleted');
        void this.router.navigate(['/inventory/movements']);
      },
      error: (err) => {
        this.busy.set(false);
        this.notify.error(apiErrorInfo(err).message || 'Could not delete the draft.');
      },
    });
  }

  async reverse(): Promise<void> {
    const m = this.move();
    if (!m || this.busy()) return;
    const ok = await this.confirm.ask({
      title: `Reverse ${m.number ?? 'this movement'}?`,
      message: 'A mirror movement is posted that cancels this one. Both stay on the ledger.',
      confirmText: 'Reverse',
      tone: 'danger',
    });
    if (!ok) return;
    this.busy.set(true);
    this.proxy
      .reverse_move(this.id, { reason: `Reversal of ${m.number ?? m.id}` })
      .subscribe({
        next: () => {
          this.busy.set(false);
          this.notify.success('Movement reversed');
          this.load();
        },
        error: (err) => {
          this.busy.set(false);
          this.notify.error(apiErrorInfo(err).message || 'Could not reverse the movement.');
        },
      });
  }
}
