import {
  lucideCheck,
  lucideChevronDown,
  lucideChevronRight,
  lucideFileChartColumn,
  lucideFileText,
  lucideHouse,
  lucideInbox,
  lucideKeyRound,
  lucideLayoutDashboard,
  lucideLayoutGrid,
  lucideLogOut,
  lucideMonitor,
  lucideMoon,
  lucidePanelLeft,
  lucidePlus,
  lucideScrollText,
  lucideSearch,
  lucideSettings,
  lucideShield,
  lucideSlidersHorizontal,
  lucideSun,
  lucideUser,
  lucideUsers,
  lucideX,
} from '@ng-icons/lucide';

/** Central icon registry — spread into provideIcons() once at bootstrap. */
export const appIcons = {
  lucideCheck,
  lucideChevronDown,
  lucideChevronRight,
  lucideFileChartColumn,
  lucideFileText,
  lucideHouse,
  lucideInbox,
  lucideKeyRound,
  lucideLayoutDashboard,
  lucideLayoutGrid,
  lucideLogOut,
  lucideMonitor,
  lucideMoon,
  lucidePanelLeft,
  lucidePlus,
  lucideScrollText,
  lucideSearch,
  lucideSettings,
  lucideShield,
  lucideSlidersHorizontal,
  lucideSun,
  lucideUser,
  lucideUsers,
  lucideX,
};
